name: Test IPython beamline profiles

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string

jobs:
  testing_beamline_profiles:
    name: ${{ matrix.repos.beamline_acronym }}-py311
    env:
      REPO_URL: "https://github.com/${{ matrix.repos.org }}/${{ matrix.repos.repo }}"
    strategy:
      fail-fast: false
      matrix:
        repos:
          - org: "NSLS-II-CSX"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "csx"
          - org: "NSLS-II-SRX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "srx"
          - org: "NSLS-II-SIX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "six"
          - org: "NSLS-II-HXN"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "hxn"
          - org: "NSLS-II-ISR"
            repo: "profile_analysis"
            branch: "master"
            beamline_acronym: "isr"
          - org: "NSLS-II-BMM"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "bmm"
          - org: "NSLS-II-QAS"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "qas"
          - org: "NSLS-II-IXS"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "ixs"
          - org: "NSLS-II-CHX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "chx"
          - org: "NSLS-II-CMS"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "cms"
          - org: "NSLS-II-SMI"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "smi"
          - org: "NSLS-II-ISR"
            repo: "profile_D-hutch"
            branch: "main"
            beamline_acronym: "isr"
          - org: "NSLS-II-TES"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "tes"
          - org: "NSLS-II-XFM"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "xfm"
          - org: "NSLS-II-FXI"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "fxi"

    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST_CONDA_PACKED_NAME=${{ needs.generate_conda_packd_envs.outputs.test_conda_packed_name }}" >> $GITHUB_ENV
      - name: Cache conda environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/conda_env
          key: ${{ runner.os }}-conda-${{ hashFiles('path/to/conda_env_file') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Download and extract conda environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/conda_env
          wget -O ~/.cache/conda_env/conda_env.tar.gz "https://zenodo.org/records/14862443/files/2025-1.0-py311-tiled.tar.gz"
          echo "3b1074c0827ee3baf0cdcd64917b9afa  ~/.cache/conda_env/conda_env.tar.gz" | md5sum -c -
          tar -xzf ~/.cache/conda_env/conda_env.tar.gz -C ~/.cache/conda_env

      - name: using test-action
        uses: NSLS2/gha-beamline-integration-test@2025-1.0-test
        with:
          conda_env_md5: "3b1074c0827ee3baf0cdcd64917b9afa"
          org: "${{ matrix.repos.org }}"
          repo: "${{ matrix.repos.repo }}"
          branch: "${{ matrix.repos.branch }}"
          beamline-acronym: "${{ matrix.repos.beamline_acronym }}"
